### PR TITLE
Fix certain assignments not showing up

### LINKED ISSUE #81: Some quizzes not showing up as assignments in the task menu
Certain quiz assignments are simply not showing up in the Canvas Task Extension display.

Some quizzes are visible and some not visible with the extension; they are all visible in the default Canvas To Do menu.

If you need any more information from the specific quizzes that are causing trouble for me, I'd be happy to provide it.

### PR DESCRIPTION
**Pull request by Leonerd-04**
closes #81

### CODE REVIEW

**Comment by Leonerd-04** [comment]
Sidenote: I can't properly test this myself because I don't know how to make the extension source work with my browser (Firefox). I'd appreciate any help on this front.

**Comment by jtcheng26** [comment]
Sorry about that, better docs for contributors is something I need to work on.

Running `npm run firefox` will build the extension for firefox, or use `node utils/webserver.js firefox` for dev server. Also it doesn't work on the latest node version for some reason, I just use v16.14.0.

To load it into firefox, visit about:debugging#/runtime/this-firefox, then click "Load Temporary Add-on" and select any file inside the build directory. Let me know if something doesn't work!

**Comment by Leonerd-04** [comment]
Ok, I was able to compile the extension and make the changes that fix the problem I was having. The assignments with "due_at" being null in my classes now appear in the task list. 

If any other changes should be made to this please let me know since I'm pretty new to JavaScript.

**Comment by jtcheng26** [comment]
Looks good, the only thing I'm wondering about is if there is ever a difference between "plannable_date" and "due_date" for an assignment where both are present, since plannable_date takes priority in your code. I would suggest moving it to the end of the or statements just in case. Should be good to merge after that!

**Comment by Leonerd-04** [comment]
Alright, all done.

**Pull request merged**
